name: Deploy iOS Development

on:
 push:
   branches:
     - dev

jobs:
 deploy:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v3
 
     - name: Set up ruby env
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: 2.7.2
         bundler-cache: true

    #  - name: Set up XCode version
    #    uses: maxim-lobanov/setup-xcode@v1
    #    with:
    #      xcode-version: latest-stable
 
     - name: Import Code-Signing Certificates
       uses: Apple-Actions/import-codesign-certs@v1
       with:
         p12-file-base64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
         p12-password: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}
    
     - name: Build & upload iOS binary
       run: bundle exec fastlane --env dev ios build_upload_testflight
       env:
         ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
         ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
         ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
         TEAM_ID: ${{ secrets.TEAM_ID }}
         KEYCHAIN_PATH: ~/Library/Keychains/signing_temp.keychain-db
 
     - name: Upload app-store ipa and dsyms to artifacts
       uses: actions/upload-artifact@v2
       with:
         name: app-store ipa & dsyms
         path: |
           ${{ github.workspace }}/CapGenDev.ipa
           ${{ github.workspace }}/*.app.dSYM.zip